permalink: post-:year-:month-:day_:title.html
collections:
  projects:
    output: true
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
navigation:
  -
    path: /
    name: 首頁
    title: Home
  -
    path: /news.html
    name: 消息
    title: News
  -
    path: /features.html
    name: 特色
    title: Features
  -
    path: /projects.html
    name: 專案
    title: Projects
  -
    path: /download.html
    name: 下載
    title: Download
  -
    path: /development.html
    name: 開發
    title: Development
  -
    path: /about.html
    name: 關於
    title: About
gems:
  - jekyll-feed
feed:
  path: atom.xml
name: 新酷音輸入法
description: "Chewing / 新酷音: 智慧型注音輸入法發展總部"
url: http://chewing.im
author:
  name: Chewing Core Team
  email: chewing-devel@googlegroups.com
