markdown: rdiscount
permalink: /:year/:month/:day/:title

title: "Chewing - Headquarter of Intelligent Chinese Phonetic Input Method Development - 新酷音輸入法"
title-min: "Chewing - 新酷音輸入法"
lasted_dl: "http://chewing.googlecode.com/files/win32-chewing-0.3.4.7.exe" 

navigation:
  - text: Download
    url: download.html
    class: download
  - text: Screenshot
    url: screenshot.html
    class: screenshot
  - text: FAQ
    url: faq.html
    class: faq
  - text: Get involed
    url: getinvoled.html
    class: getinvolved
  - text: About
    url: about.html
    class: about
